```{r}

library(ggplot2)
library(gridExtra)
library(RColorBrewer)
library(ggsci)
library(patchwork)
library(tidyr)
library(dplyr)
library(scales) 

mytemp<-theme(panel.background=element_rect(fill="white",colour=NA), panel.grid.major =element_blank(), panel.grid.minor = element_blank(),axis.line = element_line(colour = "black",size=0.5),axis.text.x = element_text(colour = "black"),axis.text.y =element_text(colour = "black"),
              axis.title.y=element_text(colour = "black"))

widetemp<-theme(panel.background=element_rect(fill="white",colour=NA), panel.grid.major =element_blank(), panel.grid.minor = element_blank(),axis.line = element_line(colour = "black",size=0.5),axis.text.x = element_text(angle = 30,size = 12,hjust = 1,colour = "black"),axis.text.y =element_text(size = 12,colour = "black"),
                axis.title.y=element_text(size=12,colour = "black"),legend.text=element_text(size=12))

rect_temp<-theme_bw()+theme(panel.background=element_rect(fill="white",colour=NA), panel.grid.minor = element_blank(), panel.grid.major =element_blank(),axis.text.y =element_text(colour = "black"), axis.title.y=element_text(colour = "black"))

basecol<-function(n){
  colall<-c('#d7191c','#31a354','#756bb1','#0571b0','#d95f0e','#bdbdbd')
  return(colall[c(1:n)])
}

new_palette <- c( RColorBrewer::brewer.pal(5, "Set1"),'#bdbdbd',"#f781bf")

mypal <- pal_d3(palette = "category20", alpha = 1)(14)


contrast_pal =c('#0571b0','#d7191c',"#9ecae1","#fdbb84","#3182bd","#e34a33")


```


```{r}

meta_info = read.csv("/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/metacell_summary.csv",row.names=1)
p_tab = data.frame(t(meta_info))
p_tab$Type = rownames(p_tab)
# colnames(meta_info)[1] = 'Type'
# dataset comparison
scale_factor <- 50000 

# 3. 绘图
p <- ggplot(p_tab, aes(x = Type)) +
  
  # --- 左轴图层：柱状图 (细胞数量) ---
  geom_col(aes(y = n_cell, fill = "Cell Count"), width = 0.5, alpha = 0.8) +
  # 添加柱子上的数字标签
  geom_text(aes(y = n_cell, label = n_cell), vjust = -0.5, color = "#4f46e5") +
  
  # --- 右轴图层：折线图 (非零率) ---
  # 注意：这里的 y 值必须乘以 scale_factor 才能显示在图上
  
  # scRNA 线条
  geom_line(aes(y = scRNA_nzero * scale_factor, group = 1, color = "scRNA Non-zero"), size = 1) +
  geom_point(aes(y = scRNA_nzero * scale_factor, color = "scRNA Non-zero"), size = 3) +
  # 添加 scRNA 的数值标签
  geom_text(aes(y = scRNA_nzero * scale_factor, label = percent(scRNA_nzero, accuracy = 0.1)), 
            vjust = -1.5, hjust = 1.2, color = "#10b981") +
  
  # scATAC 线条
  geom_line(aes(y = scATAC_nzero * scale_factor, group = 1, color = "scATAC Non-zero"), size = 1) +
  geom_point(aes(y = scATAC_nzero * scale_factor, color = "scATAC Non-zero"), size = 3) +
  # 添加 scATAC 的数值标签
  geom_text(aes(y = scATAC_nzero * scale_factor, label = percent(scATAC_nzero, accuracy = 0.1)), 
            vjust = -1.5, hjust = -0.2, color = "#f59e0b") +
  
  # --- 坐标轴设置 ---
  scale_y_continuous(
    # 左轴名称
    name = "Number of Cells",
    # 设置左轴范围，稍微留点空间给标签
    limits = c(0, 18000), 
    
    # 右轴设置 (sec.axis)
    # trans = ~./scale_factor 表示将图上的值除以系数，还原为真实的小数
    sec.axis = sec_axis(~ . / scale_factor, 
                        name = "Non-zero rate", 
                        labels = scales::percent)
  ) +
  
  # --- 颜色映射 ---
  # 这里定义图例的颜色
  scale_fill_manual(name = "", values = c("Cell Count" = "#818cf8")) +
  scale_color_manual(name = "", values = c("scRNA Non-zero" = "#10b981", "scATAC Non-zero" = "#f59e0b")) +
  
  # --- 主题美化 ---
  # theme_minimal(base_size = 14) +
  rect_temp +
  theme(
    # 调整图例位置
    legend.position = "top",
    legend.box = "horizontal"
  ) + xlab(NULL)
 
ggsave(p,filename="/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/data_summary.pdf",height=3.5,width=5)
```


```{r}


# 1. tf recovery
tf_peak_tf_recov <-read.csv("/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/tf_marker_tf_peak_res.csv",header=TRUE)
tf_gene_tf_recov <-read.csv("/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/tf_marker_tf_gene_res.csv",header=TRUE)


p_tab1<-rbind(tf_gene_tf_recov,tf_peak_tf_recov)
p_tab1 = subset(p_tab1,method!="Pearson")
p_tab1$GRN = c(rep("TF-Gene",4),rep("TF-Peak",4))
p_tab1$method<- plyr::mapvalues(p_tab1$method,from=c("linger_metacell_scale2_samp","linger_thres_scale2_samp","linger_metacell_scale2_ctx","linger_thres_scale2_ctx"),to=c("Metacell","Single-cell", "Metacell celltype","Single-cell celltype"))
p_tab1$method  = factor(p_tab1$method,levels = c("Metacell","Single-cell", "Metacell celltype","Single-cell celltype"))
# p<-ggplot(p_tab1,aes(x=GRN,y=Best_F1_avg,fill=method)) +geom_col(position='dodge')+rect_temp+scale_fill_manual(NULL,values=c('#d7191c','#0571b0',"#fdbb84","#9ecae1"))+xlab(NULL)+ylab("F1 score")
p<-ggplot(p_tab1,aes(x=GRN,y=Best_F1_avg,col=method,group=method)) +
         geom_linerange(
            aes(ymin = 0, ymax = Best_F1_avg), 
            position = position_dodge(width = 0.6),  # 这里可以直接用 pd
            linewidth = 1, 
            alpha = 0.8,
            col="grey"
          ) +
          geom_point(aes(col=method),
            size = 4, shape = 16,position=position_dodge(width = 0.6)
          ) +
          scale_color_manual(NULL,values=c('#d7191c','#0571b0',"#fdbb84","#9ecae1"))+xlab(NULL)+ylab("F1 score")+rect_temp
ggsave(p,filename="/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/tf_recovery.pdf",width=5,height=3)

odds1 = p_tab1[c(1,3,5,7),2]/p_tab1[c(2,4,6,8),2]
odds_tab1 = data.frame(odds=odds1,group="TF recovery")


pbmc_knock_res <-read.csv("/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/pbmc_tf_knock_res.csv",header=TRUE)
# pbmc_knock_res$method<- plyr::mapvalues(pbmc_knock_res$method,from=c("linger_metacell_scale2_samp","linger_thres_scale2_samp","linger_metacell_scale2_ctx","linger_thres_scale2_ctx"),to=c("CellGRN(metacell)","CellGRN", "CellGRN(metacell) celltype","CellGRN celltype"))
p_tab2 <- pivot_longer(pbmc_knock_res, 
                        cols = c(PRAUC, EPR, F1), # 要转换的列名
                        names_to = "metric",      # 新的分类列叫什么名字
                        values_to = "score")  

p_tab2$method<- plyr::mapvalues(p_tab2$method,from=c("linger_metacell_scale2_samp","linger_thres_scale2_samp","linger_metacell_scale2_ctx","linger_thres_scale2_ctx"),to=c("Metacell","Single-cell", "Metacell celltype","Single-cell celltype"))

p_tab2$method  = factor(p_tab2$method,levels = c("Metacell","Single-cell"))

p<-ggplot(p_tab2,aes(x=metric,y=score,col=method,group=method)) +
         geom_linerange(
            aes(ymin = 0, ymax = score), 
            position = position_dodge(width = 0.6),  # 这里可以直接用 pd
            linewidth = 1, 
            alpha = 0.8,
            col="grey"
          ) +
          geom_point(aes(col=method),
            size = 4, shape = 16,position=position_dodge(width = 0.6)
          ) +
          scale_color_manual(NULL,values=c('#d7191c','#0571b0',"#fdbb84","#9ecae1"))+xlab(NULL)+ylab("Score")+rect_temp

ggsave(p,filename="/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/pbmc_tf_knock.pdf",width=5,height=3)


odds2 = as.numeric(as.matrix(pbmc_knock_res[1,c(2,3,4)]/pbmc_knock_res[2,c(2,3,4)]))
odds_tab2 =  data.frame(odds=odds2,group="TF-Gene regu")


# 3. cd4 mpra enhancer discovery pr results.

cd4_gene_peak_tab = read.csv("/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/cd4_enhancer_gene_peak_res.csv",header=TRUE)
cd4_tf_peak_tab = read.csv("/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/cd4_enhancer_tf_peak_res.csv",header=TRUE)

p_tab3 = rbind(cd4_gene_peak_tab,cd4_tf_peak_tab)

p_tab3 <- pivot_longer(p_tab3, 
                        cols = c(PRAUC, EPR, F1), # 要转换的列名
                        names_to = "metric",      # 新的分类列叫什么名字
                        values_to = "score")  

p_tab3$method<- plyr::mapvalues(p_tab3$method,from=c("linger_metacell_scale2_samp","linger_thres_scale2_samp","linger_metacell_scale2_ctx_CD4","linger_thres_scale2_ctx_CD4"),to=c("Metacell","Single-cell", "Metacell celltype","Single-cell celltype"))

p_tab3$method  = factor(p_tab3$method,levels = c("Metacell","Single-cell", "Metacell celltype","Single-cell celltype"))

# 拆成2个吧
p_tab3_1 = p_tab3[1:12,]
p_tab3_2 = p_tab3[13:24,]

p<-ggplot(p_tab3_1,aes(x=metric,y=score,col=method,group=method)) +
         geom_linerange(
            aes(ymin = 0, ymax = score), 
            position = position_dodge(width = 0.6),  # 这里可以直接用 pd
            linewidth = 1, 
            alpha = 0.8,
            col="grey"
          ) +
          geom_point(aes(col=method),
            size = 4, shape = 16,position=position_dodge(width = 0.6)
          ) +
          scale_color_manual(NULL,values=c('#d7191c','#0571b0',"#fdbb84","#9ecae1"))+xlab(NULL)+ylab("Score")+rect_temp

ggsave(p,filename="/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/pbmc_enhancer_peak_gene.pdf",width=5,height=3)


p<-ggplot(p_tab3_2,aes(x=metric,y=score,col=method,group=method)) +
         geom_linerange(
            aes(ymin = 0, ymax = score), 
            position = position_dodge(width = 0.6),  # 这里可以直接用 pd
            linewidth = 1, 
            alpha = 0.8,
            col="grey"
          ) +
          geom_point(aes(col=method),
            size = 4, shape = 16,position=position_dodge(width = 0.6)
          ) +
          scale_color_manual(NULL,values=c('#d7191c','#0571b0',"#fdbb84","#9ecae1"))+xlab(NULL)+ylab("Score")+rect_temp

ggsave(p,filename="/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/pbmc_enhancer_tf_peak.pdf",width=5,height=3)


odds3 = c(as.numeric(as.matrix(cd4_gene_peak_tab[1,c(2,3,4)]/cd4_gene_peak_tab[2,c(2,3,4)])), as.numeric(as.matrix(cd4_gene_peak_tab[3,c(2,3,4)]/cd4_gene_peak_tab[4,c(2,3,4)])),as.numeric(as.matrix(cd4_tf_peak_tab[1,c(2,3,4)]/cd4_tf_peak_tab[2,c(2,3,4)])), as.numeric(as.matrix(cd4_tf_peak_tab[3,c(2,3,4)]/cd4_tf_peak_tab[4,c(2,3,4)])))
odds_tab3 =  data.frame(odds=odds3,group="Enhancer discovery")


pbmc_hic_gene_peak_tab = read.csv("/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/pbmc_ctx_hic_res.csv",header=TRUE)
pbmc_eqtl_gene_peak_tab = read.csv("/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/pbmc_ctx_eQTL_res.csv",header=TRUE)


p_tab4_1 = pivot_longer(pbmc_hic_gene_peak_tab, 
                        cols = c(PRAUC, EPR, F1), # 要转换的列名
                        names_to = "metric",      # 新的分类列叫什么名字
                        values_to = "score")  
p_tab4_2 = pivot_longer(pbmc_eqtl_gene_peak_tab, 
                        cols = c(PRAUC, EPR, F1), # 要转换的列名
                        names_to = "metric",      # 新的分类列叫什么名字
                        values_to = "score")
p_tab4_1$method<- plyr::mapvalues(p_tab4_1$method,from=c("linger_metacell_scale2_samp","linger_thres_scale2_samp","linger_metacell_scale2_ctx","linger_thres_scale2_ctx"),to=c("Metacell","Single-cell", "Metacell celltype","Single-cell celltype"))
p_tab4_2$method<- plyr::mapvalues(p_tab4_2$method,from=c("linger_metacell_scale2_samp","linger_thres_scale2_samp","linger_metacell_scale2_ctx","linger_thres_scale2_ctx"),to=c("Metacell","Single-cell", "Metacell celltype","Single-cell celltype"))
p_tab4_1$method  = factor(p_tab4_1$method,levels = c("Metacell","Single-cell", "Metacell celltype","Single-cell celltype"))
p_tab4_2$method  = factor(p_tab4_2$method,levels = c("Metacell","Single-cell", "Metacell celltype","Single-cell celltype"))

p_tab4_1$metric = paste( p_tab4_1$metric, p_tab4_1$celltype)
p<-ggplot(p_tab4_1,aes(x=metric,y=score,col=method,group=method)) +
         geom_linerange(
            aes(ymin = 0, ymax = score), 
            position = position_dodge(width = 0.6),  # 这里可以直接用 pd
            linewidth = 1, 
            alpha = 0.8,
            col="grey"
          ) +
          geom_point(aes(col=method),
            size = 4, shape = 16,position=position_dodge(width = 0.6)
          ) +
          scale_color_manual(NULL,values=c('#d7191c','#0571b0',"#fdbb84","#9ecae1"))+xlab(NULL)+ylab("Score")+rect_temp

ggsave(p,filename="/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/pbmc_hic_peak_gene.pdf",width=12,height=3)

p_tab4_2$metric = paste( p_tab4_2$metric, p_tab4_2$celltype )

p<-ggplot(p_tab4_2,aes(x=metric,y=score,col=method,group=method)) +
         geom_linerange(
            aes(ymin = 0, ymax = score), 
            position = position_dodge(width = 0.6),  # 这里可以直接用 pd
            linewidth = 1, 
            alpha = 0.8,
            col="grey"
          ) +
          geom_point(aes(col=method),
            size = 4, shape = 16,position=position_dodge(width = 0.6)
          ) +
          scale_color_manual(NULL,values=c('#d7191c','#0571b0',"#fdbb84","#9ecae1"))+xlab(NULL)+ylab("Score")+rect_temp

ggsave(p,filename="/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/pbmc_eQTL_peak_gene.pdf",width=12,height=3)

odds4=c()
for (i in seq(1,16,2)){
  odds_tmp = c(as.numeric(as.matrix(pbmc_hic_gene_peak_tab[i,c(2,3,4)]/pbmc_hic_gene_peak_tab[i+1,c(2,3,4)])),
               as.numeric(as.matrix(pbmc_hic_gene_peak_tab[i,c(2,3,4)]/pbmc_hic_gene_peak_tab[i+1,c(2,3,4)]) ))
  odds4 = c(odds4,odds_tmp)
}
odds_tab4 =  data.frame(odds=odds4,group="Gene-Peak regu")

p_tab<-rbind(odds_tab1,odds_tab2,odds_tab3,odds_tab4)
p<-ggplot(p_tab,aes(x=group,y=odds,col=group))+geom_boxplot(width=0.4)+geom_jitter(width=0.2,height=0)+rect_temp+scale_color_manual(NULL,values=mypal)+xlab(NULL) +ylab("Odds ratio(Metacell/Cell)")+ylim(c(0.9,1.1))
ggsave(p,filename="/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/metacell_odds.pdf",width=6,height=3)

write.table(p_tab,file = "/home/shaliu_fu/multireg/cellGRN/eval/results/pbmc_metacell/metacell_odds_summary.txt")
```


